@extends('layouts.app')

@section('title', 'Team | Dashora Admin Dashboard')

@section('content')
        <div class="page-title">
          <nav class="page-breadcrumb" aria-label="breadcrumb">
            <ol>
              <li><a class="page-breadcrumb-home" href="index.html"><i class="bi bi-house-door"></i><span>Home</span></a></li>
              <li class="page-breadcrumb-separator" aria-hidden="true"><i class="bi bi-chevron-right"></i></li>
              <li aria-current="page"><h1>Team</h1></li>
            </ol>
          </nav>
          <div class="page-actions"><button class="btn btn-primary" data-create-open data-create-type="team" data-create-label="Add Member"><i class="bi bi-plus-lg"></i> Add Member</button></div>
        </div>
        <h2 class="visually-hidden">Overview</h2>
        <div class="project-summary team-summary">
  <div class="summary-tile blue"><i class="bi bi-people"></i><div><strong>42</strong><span>Total Members</span></div></div><div class="summary-tile green"><i class="bi bi-person-check"></i><div><strong>36</strong><span>Active Today</span></div></div><div class="summary-tile amber"><i class="bi bi-shield-lock"></i><div><strong>8</strong><span>Admin Roles</span></div></div><div class="summary-tile violet"><i class="bi bi-diagram-3"></i><div><strong>6</strong><span>Departments</span></div></div>
</div>
<div class="panel local-filter-bar mt-4"><div class="search local-search"><i class="bi bi-search"></i><input type="search" placeholder="Search team by name, role, department..." aria-label="Search team" data-local-search="#teamGrid"></div><div class="filter-meta"><span data-local-count>6 members</span></div></div>
<div class="row g-4 mt-1" id="teamGrid">
  <div class="col-md-6 col-xl-4" data-local-item><article class="team-card"><div class="team-card-top"><span class="avatar xl online has-photo"><img src="{{ asset('assets/img/team/team-2.jpg') }}" alt="Sara Ahmed"></span><button class="icon-btn" type="button" aria-label="Member actions"><i class="bi bi-three-dots"></i></button></div><h3>Sara Ahmed</h3><p>Product Design Lead</p><div class="team-tags"><span>Design</span><span>Admin</span></div><div class="team-stats"><div><strong>18</strong><span>Projects</span></div><div><strong>96%</strong><span>Load</span></div><div><strong>4.9</strong><span>Score</span></div></div><div class="team-actions"><button class="btn btn-light btn-sm"><i class="bi bi-chat-dots"></i> Message</button><button class="btn btn-primary btn-sm"><i class="bi bi-person-gear"></i> Manage</button></div></article></div>
  <div class="col-md-6 col-xl-4" data-local-item><article class="team-card"><div class="team-card-top"><span class="avatar xl online has-photo"><img src="{{ asset('assets/img/team/team-3.jpg') }}" alt="Maya Rahman"></span><button class="icon-btn" type="button" aria-label="Member actions"><i class="bi bi-three-dots"></i></button></div><h3>Maya Rahman</h3><p>Customer Success Lead</p><div class="team-tags"><span>Success</span><span>Manager</span></div><div class="team-stats"><div><strong>24</strong><span>Accounts</span></div><div><strong>88%</strong><span>Load</span></div><div><strong>4.8</strong><span>Score</span></div></div><div class="team-actions"><button class="btn btn-light btn-sm"><i class="bi bi-chat-dots"></i> Message</button><button class="btn btn-primary btn-sm"><i class="bi bi-person-gear"></i> Manage</button></div></article></div>
  <div class="col-md-6 col-xl-4" data-local-item><article class="team-card"><div class="team-card-top"><span class="avatar xl away has-photo"><img src="{{ asset('assets/img/team/team-4.jpg') }}" alt="Jon Lee"></span><button class="icon-btn" type="button" aria-label="Member actions"><i class="bi bi-three-dots"></i></button></div><h3>Jon Lee</h3><p>Engineering Manager</p><div class="team-tags"><span>Engineering</span><span>Owner</span></div><div class="team-stats"><div><strong>11</strong><span>Sprints</span></div><div><strong>74%</strong><span>Load</span></div><div><strong>4.7</strong><span>Score</span></div></div><div class="team-actions"><button class="btn btn-light btn-sm"><i class="bi bi-chat-dots"></i> Message</button><button class="btn btn-primary btn-sm"><i class="bi bi-person-gear"></i> Manage</button></div></article></div>
  <div class="col-md-6 col-xl-4" data-local-item><article class="team-card"><div class="team-card-top"><span class="avatar xl online has-photo"><img src="{{ asset('assets/img/team/team-5.jpg') }}" alt="Priya Shah"></span><button class="icon-btn" type="button" aria-label="Member actions"><i class="bi bi-three-dots"></i></button></div><h3>Priya Shah</h3><p>Finance Partner</p><div class="team-tags"><span>Finance</span><span>Billing</span></div><div class="team-stats"><div><strong>32</strong><span>Invoices</span></div><div><strong>69%</strong><span>Load</span></div><div><strong>4.6</strong><span>Score</span></div></div><div class="team-actions"><button class="btn btn-light btn-sm"><i class="bi bi-chat-dots"></i> Message</button><button class="btn btn-primary btn-sm"><i class="bi bi-person-gear"></i> Manage</button></div></article></div>
  <div class="col-md-6 col-xl-4" data-local-item><article class="team-card"><div class="team-card-top"><span class="avatar xl has-photo"><img src="{{ asset('assets/img/team/team-1.jpg') }}" alt="Donald Risher"></span><button class="icon-btn" type="button" aria-label="Member actions"><i class="bi bi-three-dots"></i></button></div><h3>Donald Risher</h3><p>CRM Strategist</p><div class="team-tags"><span>Sales</span><span>Pipeline</span></div><div class="team-stats"><div><strong>14</strong><span>Deals</span></div><div><strong>81%</strong><span>Load</span></div><div><strong>4.5</strong><span>Score</span></div></div><div class="team-actions"><button class="btn btn-light btn-sm"><i class="bi bi-chat-dots"></i> Message</button><button class="btn btn-primary btn-sm"><i class="bi bi-person-gear"></i> Manage</button></div></article></div>
  <div class="col-md-6 col-xl-4" data-local-item><article class="team-card"><div class="team-card-top"><span class="avatar xl online has-photo"><img src="{{ asset('assets/img/team/team-6.jpg') }}" alt="Ariana Reed"></span><button class="icon-btn" type="button" aria-label="Member actions"><i class="bi bi-three-dots"></i></button></div><h3>Ariana Reed</h3><p>Support Operations</p><div class="team-tags"><span>Support</span><span>SLA</span></div><div class="team-stats"><div><strong>46</strong><span>Tickets</span></div><div><strong>92%</strong><span>Load</span></div><div><strong>4.9</strong><span>Score</span></div></div><div class="team-actions"><button class="btn btn-light btn-sm"><i class="bi bi-chat-dots"></i> Message</button><button class="btn btn-primary btn-sm"><i class="bi bi-person-gear"></i> Manage</button></div></article></div>
  <div class="col-12" data-local-empty hidden><div class="empty-state local-empty"><i class="bi bi-search"></i><h2>No members found</h2><p>Try searching by member name, role, department, or permission level.</p></div></div>
</div>
<div class="row g-4 mt-1"><div class="col-xl-8"><div class="panel"><div class="panel-head"><div><h2>Department Capacity</h2><p>Team allocation and workload by function</p></div><button class="btn btn-sm btn-light">View roster</button></div><div class="roadmap-list team-capacity"><div class="roadmap-item blue"><span>Design</span><div><strong>Design Systems</strong><div class="progress"><div class="progress-bar" style="width:82%"></div></div></div><em>82%</em></div><div class="roadmap-item green"><span>CS</span><div><strong>Customer Success</strong><div class="progress"><div class="progress-bar" style="width:74%"></div></div></div><em>74%</em></div><div class="roadmap-item amber"><span>Eng</span><div><strong>Engineering</strong><div class="progress"><div class="progress-bar" style="width:68%"></div></div></div><em>68%</em></div><div class="roadmap-item violet"><span>Ops</span><div><strong>Support Operations</strong><div class="progress"><div class="progress-bar" style="width:91%"></div></div></div><em>91%</em></div></div></div></div><div class="col-xl-4"><div class="panel"><div class="panel-head"><div><h2>Access Activity</h2><p>Recent permissions and invites</p></div></div><div class="timeline"><div class="timeline-item"><span></span><div><strong>Sara Ahmed granted design-system admin access</strong><small>8 min ago</small></div></div><div class="timeline-item"><span></span><div><strong>Ariana Reed joined Support Operations</strong><small>24 min ago</small></div></div><div class="timeline-item"><span></span><div><strong>Finance role policy was updated</strong><small>1 hr ago</small></div></div><div class="timeline-item"><span></span><div><strong>Two pending invites expire tomorrow</strong><small>3 hr ago</small></div></div></div></div></div></div>
@endsection
