@extends('pdf.layout')

@php
    $titles = [
        'income' => 'Income Report',
        'expense' => 'Expense Report',
        'profit_loss' => 'Profit & Loss Statement',
    ];
@endphp

@section('title', $titles[$reportType].' — '.$globalSettings->villa_name)

@section('content')

    <table class="header-table">
        <tr>
            <td style="width: 55%;">
                @if ($globalSettings->villa_logo && file_exists(public_path('storage/'.$globalSettings->villa_logo)))
                    <img class="villa-logo" src="{{ public_path('storage/'.$globalSettings->villa_logo) }}">
                @endif
                <div class="villa-name">{{ $globalSettings->villa_name }}</div>
                <div class="muted">
                    @if ($globalSettings->address){{ $globalSettings->address }}<br>@endif
                    @if ($globalSettings->phone_number){{ $globalSettings->phone_number }}<br>@endif
                    @if ($globalSettings->email){{ $globalSettings->email }}@endif
                </div>
            </td>
            <td style="width: 45%;">
                <div class="doc-title">{{ $titles[$reportType] }}</div>
                <div class="muted text-right">Period: {{ $periodLabel }}</div>
                <div class="muted text-right">Generated: {{ now()->format('d M Y, H:i') }}</div>
            </td>
        </tr>
    </table>

    @if ($reportType !== 'expense')
        <div class="section-title">Income Transactions</div>
        <table class="items-table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Type</th>
                    <th>Customer</th>
                    <th>Room</th>
                    <th class="text-right">Amount</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($incomeRows as $row)
                    <tr>
                        <td>{{ $row['date']->format('d M Y') }}</td>
                        <td>{{ $row['type'] }}</td>
                        <td>{{ $row['booking']->customer_name }}</td>
                        <td>{{ $row['booking']->room->name_or_number }}</td>
                        <td class="text-right">{{ $globalSettings->currency }} {{ number_format($row['amount'], 2) }}</td>
                    </tr>
                @empty
                    <tr><td colspan="5" class="muted" style="text-align: center;">No income recorded for this period.</td></tr>
                @endforelse
            </tbody>
        </table>
    @endif

    @if ($reportType !== 'income')
        <div class="section-title">Expense Transactions</div>
        <table class="items-table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Description</th>
                    <th class="text-right">Amount</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($expenseRows as $expense)
                    <tr>
                        <td>{{ $expense->expense_date->format('d M Y') }}</td>
                        <td>{{ $expense->category }}</td>
                        <td>{{ $expense->description ?: '—' }}</td>
                        <td class="text-right">{{ $globalSettings->currency }} {{ number_format($expense->amount, 2) }}</td>
                    </tr>
                @empty
                    <tr><td colspan="4" class="muted" style="text-align: center;">No expenses recorded for this period.</td></tr>
                @endforelse
            </tbody>
        </table>
    @endif

    <table class="totals-table">
        @if ($reportType !== 'expense')
            <tr>
                <td class="label">Total Revenue</td>
                <td class="value">{{ $globalSettings->currency }} {{ number_format($totalIncome, 2) }}</td>
            </tr>
        @endif
        @if ($reportType !== 'income')
            <tr>
                <td class="label">Total Expenses</td>
                <td class="value">{{ $globalSettings->currency }} {{ number_format($totalExpenses, 2) }}</td>
            </tr>
        @endif
        @if ($reportType === 'profit_loss')
            <tr class="grand">
                <td class="label">Net Profit</td>
                <td class="value" style="color: {{ $netProfit >= 0 ? '#2fa84f' : '#dc2626' }};">{{ $globalSettings->currency }} {{ number_format($netProfit, 2) }}</td>
            </tr>
        @endif
    </table>

    <div class="footer-note">
        Generated by {{ $globalSettings->villa_name }} — Villa Management System.
    </div>

@endsection
